In [61]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [62]:
data=pd.read_csv("/content/covid_grouped.csv")
data

,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region,iso_alpha
0,2020-01-22,Afghanistan,0,0,0,0,0,0,0,Eastern Mediterranean,AFG
1,2020-01-22,Albania,0,0,0,0,0,0,0,Europe,ALB
2,2020-01-22,Algeria,0,0,0,0,0,0,0,Africa,DZA
3,2020-01-22,Andorra,0,0,0,0,0,0,0,Europe,AND
4,2020-01-22,Angola,0,0,0,0,0,0,0,Africa,AGO
...,...,...,...,...,...,...,...,...,...,...,...
35151,2020-07-27,West Bank and Gaza,10621,78,3752,6791,152,2,0,Eastern Mediterranean,
35152,2020-07-27,Western Sahara,10,1,8,1,0,0,0,Africa,ESH
35153,2020-07-27,Yemen,1691,483,833,375,10,4,36,Eastern Mediterranean,YEM
35154,2020-07-27,Zambia,4552,140,2815,1597,71,1,465,Africa,ZMB
35155,2020-07-27,Zimbabwe,2704,36,542,2126,192,2,24,Africa,ZWE

In [63]:
data.shape

(35156, 11)

In [64]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35156 entries, 0 to 35155
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            35156 non-null  object
 1   Country/Region  35156 non-null  object
 2   Confirmed       35156 non-null  int64
 3   Deaths          35156 non-null  int64
 4   Recovered       35156 non-null  int64
 5   Active          35156 non-null  int64
 6   New cases       35156 non-null  int64
 7   New deaths      35156 non-null  int64
 8   New recovered   35156 non-null  int64
 9   WHO Region      35156 non-null  object
 10  iso_alpha       35156 non-null  object
dtypes: int64(7), object(4)
memory usage: 3.0+ MB

In [65]:
data.describe()

,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered
count,3.515600e+04,35156.000000,3.515600e+04,3.515600e+04,35156.00000,35156.000000,35156.000000
mean,2.356663e+04,1234.068239,1.104813e+04,1.128443e+04,469.36375,18.603339,269.315593
std,1.499818e+05,7437.238354,6.454640e+04,8.997149e+04,3005.86754,115.706351,2068.063852
min,0.000000e+00,0.000000,0.000000e+00,-2.000000e+00,0.00000,-1918.000000,-16298.000000
25%,1.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.00000,0.000000,0.000000
50%,2.500000e+02,4.000000,3.300000e+01,8.500000e+01,2.00000,0.000000,0.000000
75%,3.640250e+03,78.250000,1.286250e+03,1.454000e+03,75.00000,1.000000,20.000000
max,4.290259e+06,148011.000000,1.846641e+06,2.816444e+06,77255.00000,3887.000000,140050.000000

In [66]:
data.isna().sum()

Date              0
Country/Region    0
Confirmed         0
Deaths            0
Recovered         0
Active            0
New cases         0
New deaths        0
New recovered     0
WHO Region        0
iso_alpha         0
dtype: int64

In [67]:
data.columns = (
    data.columns
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("/", "_")
)

In [68]:
data["date"] = pd.to_datetime(data["date"])

In [69]:
data

,date,country_region,confirmed,deaths,recovered,active,new_cases,new_deaths,new_recovered,who_region,iso_alpha
0,2020-01-22,Afghanistan,0,0,0,0,0,0,0,Eastern Mediterranean,AFG
1,2020-01-22,Albania,0,0,0,0,0,0,0,Europe,ALB
2,2020-01-22,Algeria,0,0,0,0,0,0,0,Africa,DZA
3,2020-01-22,Andorra,0,0,0,0,0,0,0,Europe,AND
4,2020-01-22,Angola,0,0,0,0,0,0,0,Africa,AGO
...,...,...,...,...,...,...,...,...,...,...,...
35151,2020-07-27,West Bank and Gaza,10621,78,3752,6791,152,2,0,Eastern Mediterranean,
35152,2020-07-27,Western Sahara,10,1,8,1,0,0,0,Africa,ESH
35153,2020-07-27,Yemen,1691,483,833,375,10,4,36,Eastern Mediterranean,YEM
35154,2020-07-27,Zambia,4552,140,2815,1597,71,1,465,Africa,ZMB
35155,2020-07-27,Zimbabwe,2704,36,542,2126,192,2,24,Africa,ZWE

In [70]:
num_cols = [
    "confirmed","deaths","recovered","active",
    "new_cases","new_deaths","new_recovered"
]

for col in num_cols:
    data[col] = pd.to_numeric(data[col], errors="coerce")

In [71]:
data.columns

Index(['date', 'country_region', 'confirmed', 'deaths', 'recovered', 'active',
       'new_cases', 'new_deaths', 'new_recovered', 'who_region', 'iso_alpha'],
      dtype='object')

In [72]:
data['Death Rate'] = np.where(data['confirmed']>0, data['deaths']/data['confirmed'], 0)
data['Recovery Rate'] = np.where(data['confirmed']>0, data['recovered']/data['confirmed'], 0)
data['Active Rate'] = np.where(data['confirmed']>0, data['active']/data['confirmed'], 0)

In [73]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35156 entries, 0 to 35155
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            35156 non-null  datetime64[ns]
 1   country_region  35156 non-null  object
 2   confirmed       35156 non-null  int64
 3   deaths          35156 non-null  int64
 4   recovered       35156 non-null  int64
 5   active          35156 non-null  int64
 6   new_cases       35156 non-null  int64
 7   new_deaths      35156 non-null  int64
 8   new_recovered   35156 non-null  int64
 9   who_region      35156 non-null  object
 10  iso_alpha       35156 non-null  object
 11  Death Rate      35156 non-null  float64
 12  Recovery Rate   35156 non-null  float64
 13  Active Rate     35156 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(7), object(3)
memory usage: 3.8+ MB

In [74]:
data["year"] = data["date"].dt.year
data["month"] = data["date"].dt.month
data["day"] = data["date"].dt.day
data["dayofweek"] = data["date"].dt.dayofweek

In [75]:
data["cases_7d_avg"] = (
    data.groupby("country_region")["new_cases"]
    .transform(lambda x: x.rolling(7).mean())
)

data["deaths_7d_avg"] = (
    data.groupby("country_region")["new_deaths"]
    .transform(lambda x: x.rolling(7).mean())
)

In [76]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data['Country_Code'] = le.fit_transform(data['country_region'])

le_region = LabelEncoder()
data['Region_Code'] = le.fit_transform(data['who_region'])

data['iso_alpha'] = le.fit_transform(data['iso_alpha'])

In [77]:
data = data.sort_values(['country_region', 'date']).reset_index(drop=True)
data.drop(columns=['country_region','who_region'] , inplace=True)

In [78]:
data

,date,confirmed,deaths,recovered,active,new_cases,new_deaths,new_recovered,iso_alpha,Death Rate,Recovery Rate,Active Rate,year,month,day,dayofweek,cases_7d_avg,deaths_7d_avg,Country_Code,Region_Code
0,2020-01-22,0,0,0,0,0,0,0,1,0.000000,0.000000,0.000000,2020,1,22,2,NaN,NaN,0,2
1,2020-01-23,0,0,0,0,0,0,0,1,0.000000,0.000000,0.000000,2020,1,23,3,NaN,NaN,0,2
2,2020-01-24,0,0,0,0,0,0,0,1,0.000000,0.000000,0.000000,2020,1,24,4,NaN,NaN,0,2
3,2020-01-25,0,0,0,0,0,0,0,1,0.000000,0.000000,0.000000,2020,1,25,5,NaN,NaN,0,2
4,2020-01-26,0,0,0,0,0,0,0,1,0.000000,0.000000,0.000000,2020,1,26,6,NaN,NaN,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35151,2020-07-23,2124,28,510,1586,90,2,0,178,0.013183,0.240113,0.746704,2020,7,23,3,108.857143,0.714286,186,0
35152,2020-07-24,2296,32,514,1750,172,4,4,178,0.013937,0.223868,0.762195,2020,7,24,4,125.142857,1.142857,186,0
35153,2020-07-25,2434,34,518,1882,138,2,4,178,0.013969,0.212818,0.773213,2020,7,25,5,136.571429,1.285714,186,0
35154,2020-07-26,2512,34,518,1960,78,0,0,178,0.013535,0.206210,0.780255,2020,7,26,6,128.714286,1.285714,186,0
35155,2020-07-27,2704,36,542,2126,192,2,24,178,0.013314,0.200444,0.786243,2020,7,27,0,141.571429,1.428571,186,0

In [81]:
data.fillna(0, inplace=True)
data[['cases_7d_avg', 'deaths_7d_avg']] = data[['cases_7d_avg', 'deaths_7d_avg']].interpolate()

In [82]:
data.head()

,date,confirmed,deaths,recovered,active,new_cases,new_deaths,new_recovered,iso_alpha,Death Rate,Recovery Rate,Active Rate,year,month,day,dayofweek,cases_7d_avg,deaths_7d_avg,Country_Code,Region_Code
0,2020-01-22,0,0,0,0,0,0,0,1,0.0,0.0,0.0,2020,1,22,2,0.0,0.0,0,2
1,2020-01-23,0,0,0,0,0,0,0,1,0.0,0.0,0.0,2020,1,23,3,0.0,0.0,0,2
2,2020-01-24,0,0,0,0,0,0,0,1,0.0,0.0,0.0,2020,1,24,4,0.0,0.0,0,2
3,2020-01-25,0,0,0,0,0,0,0,1,0.0,0.0,0.0,2020,1,25,5,0.0,0.0,0,2
4,2020-01-26,0,0,0,0,0,0,0,1,0.0,0.0,0.0,2020,1,26,6,0.0,0.0,0,2